[[redirects]]
  from = "/api/cpf-lookup/*"
  to = "/.netlify/functions/cpf/:splat"
  status = 200

[[redirects]]
  from = "/api/create-pix"
  to = "/.netlify/functions/create-pix"
  status = 200

[[redirects]]
  from = "/api/check-pix/*"
  to = "/.netlify/functions/check-pix/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
